### ISSUE TITLE
Can't open files with leading space characters

### ISSUE THREAD

**Issue by ddiget** [mvz/email-outlook-message-perl#10]
I was processing an Office 365 Individual Message export and it created some msg files with **leading** spaces in the filename.  (Since the filenames are based on the message Subject, this is understandable.)

I modified my local copy of message.pm for line 114 so that it used the filehandle object way as given in the second example of the synopis at http://search.cpan.org/~jmcnamara/OLE-Storage_Lite-0.19/lib/OLE/Storage_Lite.pm
```

--- Message.pm.orig	2015-07-04 19:20:08.000000000 -0400
+++ Message.pm	2018-01-04 14:57:08.352770214 -0500
@@ -111,7 +111,13 @@
 
   $self->{EMBEDDED} = 0;
 
-  my $msg = OLE::Storage_Lite->new($file);
+  use IO::File;
+  my $oIo = new IO::File;
+  $oIo->open("$file", "r" ,0666);
+  binmode($oIo);
+  my $msg = OLE::Storage_Lite->new($oIo);
+
+  #my $msg = OLE::Storage_Lite->new($file);
   my $pps = $msg->getPpsTree(1);
   $pps or croak "Parsing $file as OLE file failed";
   $self->_set_verbosity($verbose);
```

and it solved the problem for me (or at least I not longer got the croak error message.

**Comment by mvz** [comment]
Thanks, @ddiget, I'll look into it.

**Comment by bf** [comment]
@ddiget can you create a pull request so @mvz can easily merge and resolve this issue?

**Comment by mvz** [comment]
It makes more sense to me to have this fixed in OLE::Storage_Lite. The problems seems to be on this line: https://github.com/jmcnamara/ole-storage-lite/blob/f4a3f341b414bbe73808e4470e1f3c799c05679a/lib/OLE/Storage_Lite.pm#L920

**Comment by mvz** [comment]
A fix for this has been accepted in OLE::Storage_Lite and should be available as soon as a new version is released.
