### ISSUE TITLE
line endings on unix system

### ISSUE THREAD

**Issue by fanto666** [mvz/email-outlook-message-perl#13]
hello,
msgconvert writes files in dos format. It would be great if it could strip CR characters on unix systems.

**Comment by mvz** [comment]
Hi @fanto666, headers in the RFC 2822 format are separated by CRLF, regardless of being on dos or unix systems.

**Comment by mvz** [comment]
Closing this since this should not be changed.

**Comment by fanto666** [comment]
I am really sorry for missing the last message
Headerd on the fly sure use the CR+LF format, however 
1. when storing to file, the system line-ending should be used
2. the separating "From " line uses system ending.

**Comment by mvz** [comment]
I'm pretty sure the current behavior is correct:
* I just saved an .eml file from Thunderbird on Linux, and it also uses CR+LF format.
* I'm using the Email::Sender::Transport::Mbox and Email::MIME packages and this is the result they give.
If you still feel a change is needed, it's best to file a bug with Email::Sender::Transport::Mbox and/or Email::MIME.
