### ISSUE TITLE
charset name UTF8 do not conform IANA

### ISSUE THREAD

**Issue by dekorfa** [mvz/email-outlook-message-perl#33]
I tested msgconvert recently and got a quite well formated .eml file.
But I notice this multipart header in the resulting .eml :

--16153750240.8B52dA.31571
Content-Type: text/plain; charset="UTF8"
Content-Transfer-Encoding: 8bit
Content-Disposition: inline

Another software (proprietary one) displaying the mail complain about the charset name UTF8. In the IANA charset list (http://www.iana.org/assignments/character-sets/character-sets.xhtml), I can see "UTF-8" and the alias "csUTF8", but no "UTF8".

Could it be possible to modify the produced charset to "UTF-8" instead of "UTF8" ?

**Comment by mvz** [comment]
Hi @dekorfa thanks for your bug report. Can you tell me which version of Email::Outlook::Message you're using?

**Comment by mvz** [comment]
@dekorfa the reason I'm asking for the version is that the current version should already produce UTF-8 as per 66aacc357aaac46a6d2306f2e3f22b27289a7bec, which was included in version 0.919.

**Comment by dekorfa** [comment]
Actually, I use the msgconvert command from the debian package libemail-outlook-message-perl 0.918-2 on a debian 9. I see that this version do not include the commit you mentionned. I will switch to the new version.
Thanks a lot for your reply.
