### ISSUE TITLE
codepage CP28592 unknown

### ISSUE THREAD

**Issue by fanto666** [mvz/email-outlook-message-perl#39]
Hello,
I have received this error using msgconvert:

% msgconvert --mbox spam FW_chyba_VUK_pri_UZ.msg
Unknown encoding 'CP28592' at /usr/share/perl5/Email/Outlook/Message.pm line 399

adding the following to  $MAP_CODEPAGE helped:

 28592 => 'ISO-8859-2',

**Comment by mvz** [comment]
Thanks, @fanto666, I'll look into it.
