### ISSUE TITLE
Does it support the reverse conversion?

### ISSUE THREAD

**Issue by ss-dsutherland** [mvz/email-outlook-message-perl#62]
The docs don't appear to specify it does but I'm wondering is it possible with this tool (or the same libraries) to take an eml file and convert it to .msg file.  I'm aiming to use this as part of an apache nifi workflow on a linux host

**Comment by mvz** [comment]
Hi @ss-dsutherland, no, this library does not support the reverse conversion. Once upon a time I considered adding that ability, but it would require fundamental changes to the code. It is highly unlikely that I will ever add support for this.
