### ISSUE TITLE
Conversion to .eml in Windows - extra newlines break attachments

### ISSUE THREAD

**Issue by Loo0D** [mvz/email-outlook-message-perl#8]
Conversion to .eml in Windows 10 (v5.24.1, MSWin32-x64-multi-thread, Strawberry Perl inside Cygwin) adds a form of "newline" to each line (not just base64).  As a result (?) attachments are not recognised as files by email client, and base64 is simply inlined into the message body.

---mbox generation unaffected.

Under Linux conversion to .eml of same .msg succeeds as expected.

Example message body snippet where it transitions to the attachment, whitespace retained: 

```
==========[SNIP BEGINS]===================================
<p class=MsoNormal><font size=3 face="Times New Roman"><span lang=EN-US

style='font-size:12.0pt'><o:p>&nbsp;</o:p></span></font></p>



</div>



</body>



</html>



--14901086630.FEb4.8904

Content-Type: application/rtf

Content-Disposition: inline

Content-Transfer-Encoding: base64



e1xydGYxXGFuc2lcYW5zaWNwZzEyNTJcZnJvbWh0bWwxIFxkZWZmMHtcZm9udHRibAoNe1xmMFxm

c3dpc3MgQXJpYWw7fQoNe1xmMVxmbW9kZXJuIENvdXJpZXIgTmV3O30KDXtcZjJcZm5pbFxmY2hh

cnNldDIgU3ltYm9sO30KDXtcZjNcZm1vZGVyblxmY2hhcnNldDAgQ291cmllciBOZXc7fQoNe1xm

NFxmc3dpc3NcZmNoYXJzZXQwIEFyaWFsO30KDXtcZjVcZnN3aXNzXGZjaGFyc2V0MCBUaW1lcyBO

ZXcgUm9tYW47fQoNe1xmNlxmbmlsXGZjaGFyc2V0MiBXaW5nZGluZ3M7fQoNe1xmN1xmbmlsXGZj
==========[SNIP ENDS]===================================
```

**Comment by mvz** [comment]
@granite-zero which version of Email::Outlook:Message were you using and can you still reproduce it with the current version (0.919)?

**Comment by Loo0D** [comment]
Afraid I no longer have the offending files, will close issue and re-open if needed.
